### ISSUE TITLE
Author name,Author Image  and bio should be added

### ISSUE THREAD

**Issue by uthsobcb** [Prog-Theta/Blog-Author-Profile#2]
It's very important to add author name,image and bio in Author profile card

**Comment by anikakash** [comment]
sure if you can add it then go-ahead

**Comment by uthsobcb** [comment]
Done! Here your preview
![Screenshot_2021-05-23_23-21-44](https://user-images.githubusercontent.com/51291526/119270282-cb8cae00-bc1d-11eb-8ed1-6faf08be893e.png)

**Comment by anikakash** [comment]
Great
